name: ztl
version: 0.0.0
description: Zettelkasten like
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/ztl

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -fplugin=Polysemy.Plugin

default-extensions:
  - TemplateHaskell
  - LambdaCase
  - BlockArguments
  - GADTs
  - FlexibleContexts
  - TypeOperators
  - DataKinds
  - PolyKinds
  - ScopedTypeVariables
  - OverloadedStrings
  - ImportQualifiedPost
  - RecordWildCards
  - DerivingStrategies
  - GeneralizedNewtypeDeriving

library:
  source-dirs: src
  exposed-modules:
    - Ztl
    - ZtlMark.Parser
    - ZtlMark.Type
    - ZtlMark.Parser.Internal
    - ZtlMark.Parser.Internal.Type
  dependencies:
    - base
    - polysemy
    - polysemy-plugin
    - megaparsec
    - parser-combinators
    - text
    - mtl
    - microlens
    - microlens-th
    - deepseq
    - case-insensitive
    - hashable
    - containers
    - unordered-containers >=0.2.5 && <0.3
    - modern-uri
    - text-metrics

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base
    - polysemy
    - polysemy-plugin
    - ztl
  ghc-options:
    - -Wall

tests:
  tasty:
    source-dirs: tasty
    main: Main.hs
    dependencies:
      - base
      - polysemy
      - polysemy-plugin
      - ztl
